version: "3.1"
services:
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  builder:
    build: .
    image: builder
  backend:
    depends_on:
      - builder
      - mongo
    build: ./backend
    environment:
      DATABASE_URL: mongodb://root:password@mongo:27017/analytics?authSource=admin
      NODE_ENV: production
    ports:
      - 3000:3000
  frontend:
    depends_on:
      - builder
      - backend
    build: ./frontend
    ports:
      - 8080:80
